name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: travisj/build-number-action@v1
      id: my-project-build-number
    - uses: actions/checkout@v2
    - name: Build
      run: ./build.sh
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.sha }}-release
        release_name: Release ${{ steps.my-project-build-number.outputs.build-number }}
        draft: false
        prerelease: false
    - name: Upload Release Asset (CLI)
      id: upload-release-asset-w
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./fif2png 
        asset_name: fif-cli
        asset_content_type: application/octet-stream
    - name: Upload Release Asset (SDL)
      id: upload-release-asset-w
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./fifsdl 
        asset_name: fif-sdl
        asset_content_type: application/octet-stream:  
